language: node_js
node_js:
  - "13"
script:
  - yarn lint
  - yarn build
before_deploy:
  - gem install image_optim
  - gem install image_optim_pack
  - command -v pngout || curl -L "http://www.jonof.id.au/files/kenutils/pngout-20200115-linux.tar.gz" | tar -xz -C ~/bin --strip-components 2 --wildcards '*/x86_64/pngout'
  - yarn generate-example-images
  - yarn postbuild
cache: yarn
deploy:
  edge: true
  provider: pages
  github-token: $GITHUB_TOKEN
  local-dir: dist
  name: Dominik Moritz
  email: domoritz@gmail.com
  project-name: editor
  on:
    branch: master
    tags: true
addons:
  apt:
    packages:
      - parallel
